### ISSUE TITLE
Maybe add screenshots

### ISSUE THREAD

**Issue by JoostScheffer** [Abilbel/dotfiles#1]
Just a friendly suggestion.
Adding screenshots of your desktop would really make the readme.md look cooler and more representative of the dotfiles.

**Comment by cvignal** [comment]
Oh yeah great idea, I was only using this repo privately but now that it's public it might be a good time to do that.

**Comment by cvignal** [comment]
Done !

**Comment by JoostScheffer** [comment]
Nicely done!
How did you manage to get such high resolution screenshots?

**Comment by cvignal** [comment]
I have a 2560 * 1440 monitor which is pretty nice
